### ISSUE TITLE
authenticateWithCompletionBlock:cancelBlock: not callable 

### ISSUE THREAD

**Issue by yvan** [box/box-ios-sdk#162]
Tried to follow instructions here : https://github.com/box/box-ios-sdk/blob/master/doc/Authentication.md

Found this:

<img width="1090" alt="screen shot 2016-01-09 at 2 25 56 pm" src="https://cloud.githubusercontent.com/assets/4513316/12217902/f6efd726-b6dc-11e5-8581-5e0e4117d2be.png">

It looks like the cancel block part of this method is not recognized. I took out the cancel block and it worked ok but It would be nice to register user cancels of the auth process.

I tried the second option of presenting the my own viewcontroller for authentication, but then the cancel button did not appear.

This process causes a login prompt to appear with no cancel button at all.

<img width="1064" alt="screen shot 2016-01-09 at 2 53 58 pm" src="https://cloud.githubusercontent.com/assets/4513316/12218042/1328117a-b6e1-11e5-9ab4-c121d97725a5.png">

It seems like there is an issue withe the cancel for authentication.

Note: I even compiled the sample code all and looked for the test of the `authenticateWithCompletionBlock` and found that it doesn't recognize cancelBlock there either:

<img width="1083" alt="screen shot 2016-01-09 at 3 15 50 pm" src="https://cloud.githubusercontent.com/assets/4513316/12218131/e6b43de6-b6e3-11e5-9ac5-d0f4c2fffbe5.png">

I ended up adding my own cancel button to box's auth controller.

**Comment by RicoYao** [comment]
Thanks for pointing out these issues.

I've updated the documentation for the first issue you pointed out. You can detect the cancelation, but instead of a separate cancel block, you can look at the error in the completion block. It should have domain:BOXContentSDKErrorDomain code:BOXContentSDKAPIUserCancelledError. You can see an example of this check here:

https://github.com/box/box-ios-sdk/blob/master/BoxContentSDKSampleApp/BoxContentSDKSampleApp/BOXSampleAccountsViewController.m#L63

Regarding the second issue, with the missing 'cancel' button when manually presenting the view controller, I believe the 'cancel' button would show up if you place the view controller into a UINavigationController. Here's an example of how to present:

https://github.com/box/box-ios-sdk/blob/master/BoxContentSDK/BoxContentSDK/Clients/BOXContentClient%2BAuthentication.m#L218

Again, thanks for pointing out the incorrect documentation. We'll correct it.

**Comment by yvan** [comment]
Thanks for taking to time to have a look.
