### ISSUE TITLE
Is this app runnable

### ISSUE THREAD

**Issue by saran-metron** [box/box-ios-sdk#222]
i downloaded this application and tried to run the app in IOS but its not running..can some one please help me to run this application and how to integrate with our box application

**Comment by h2kuo** [comment]
Hi @saran-metron,

Can you tell us what kind of errors you are seeing, and at which step? What Xcode version and CocoaPods version are you using?

If you're trying to run the BoxContentSDKSampleApp, you first need to run `pod install` in the BoxContentSDKSampleApp directory and open the .xcworkspace, not the .xcodeproj.

You also need to make sure you set the client ID and client secret in the BOXSampleAppDelegate, which can be obtained by following the instructions [here](https://github.com/box/box-ios-sdk/blob/master/doc/Setup.md) for creating an app.

**Comment by dzwilkerson** [comment]
Piggybacking on this issue because I'm questioning the same thing... 

I have the sample app setup and can run on a device or simulator. I try to OAuth accounts button. Tap the plus button and get this message in the console:

```
2016-06-08 16:50:44.549 BoxContentSDKSampleApp[13219:26829720] Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<BOXAuthorizationViewController: 0x786387f0>)
```

Nothing happens. I get crashes when trying the AppUser Accounts (but I'm not planning on doing enterprise accounts so I don't really care)

I originally set my app up when the SDK used to be called BoxSDK and not the BoxContentSDK... At least 18 months ago, probably more. I updated the redirect_uri on the app.box.com/developers page for my app and still nothing.

**Comment by boxtcarpel** [comment]
@dzwilkerson we recently fixed an issue that sounds like what you are describing (https://github.com/box/box-ios-sdk/pull/238) on the master branch. Can you confirm whether your testing was with that commit or not? If not, does picking up that fix resolve the issue for you? Thanks in advance.

**Comment by saran-metron** [comment]
thanku

-------- Original Message --------
Subject: Re: [box/box-ios-sdk] Is this app runnable (#222)

**Comment by tanmayGIT** [comment]
i still have the same issue; I have tried re-installing through Pods but no help
This following warning is appearing and button to upload is not working ..

`[Warning] Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<BOXAuthorizationViewController:  0x7ffb00c9f3c0>)`
