### ISSUE TITLE
BoxContentSDK.h not found

### ISSUE THREAD

**Issue by jpm165** [box/box-ios-sdk#224]
Hello,
Am I missing something? When I install this into my project using the directions for Cocoapods provided, I get about 9 or so errors that say "'BoxContentSDK/BoxContentSDK.h' file not found". This happens in BOXContentClient+Metadata.h, for example. You can clearly see it says "#import &lt;BoxContentSDK/BoxContentSDK.h&gt;" (and not BOXContentSDK.h). 

I can't believe I am the only one this is happening too, and yet nobody is mentioning it anywhere else, so what am I doing wrong?

My Podfile has one line in it: pod 'box-ios-sdk' and I literally have no other code in my project other than stock Xcode 7 template code. I just run pod install, quit Xcode, open the .xcworkspace and Command-B and get the error.

**Comment by h2kuo** [comment]
Hi @jpm165, 

Thanks for bringing up this issue. If you do replace all <BoxContentSDK/BoxContentSDK.h> with the capitalized <BoxContentSDK/BOXContentSDK.h>, is it able to compile? 

Not all machines are case sensitive, so we may have missed a couple of the import statements because it was compiling for us. We'll make sure to get this updated in the next release!

**Comment by jpm165** [comment]
Yes, I just finished up doing that right now and was able to compile everything. Thanks!

**Comment by boxtcarpel** [comment]
https://github.com/box/box-ios-sdk/pull/225
