### ISSUE TITLE
Implement metadata operations on Folder objects

### ISSUE THREAD

**Issue by boxtcarpel** [box/box-ios-sdk#235]
Currently, metadata get/set/delete operations are only exposed for files via the SDK. Support needs to be added for Folders (support has already been added to the API).

**Comment by PJSimon** [comment]
Hi @boxtcarpel !  We're closing this Enhancement Issue on the [objective-c-maintenance branch](https://github.com/box/box-ios-sdk/tree/objective-c-maintenance) since the Objective-C iOS SDK is now in "maintenance mode." We won't be able to prioritize this work.  This feature is available in the current version of the SDK (in Swift).

As a reminder, per the [README.md](https://github.com/box/box-ios-sdk/blob/master/README.md):
> The Box iOS SDK in Objective-C (prior to v3.0.0) has been moved from the master branch to the [objective-c-maintenance branch](https://github.com/box/box-ios-sdk/tree/objective-c-maintenance). Going forward, the master branch will contain the iOS SDK in Swift, starting with v3.0.0.

Thanks,

@PJSimon
