### ISSUE TITLE
Long polling on /events is not supported.

### ISSUE THREAD

**Issue by objcguy** [box/box-ios-sdk#252]
Long polling on /event doesn't seem to be implemented yet.

**Comment by thuyBox** [comment]
@objcguy , thanks for your feedback, we'll look into adding the support and let you know.

**Comment by PJSimon** [comment]
Hi @objcguy and @thuyBox !  We're closing this Enhancement Issue on the [objective-c-maintenance branch](https://github.com/box/box-ios-sdk/tree/objective-c-maintenance) since the Objective-C iOS SDK is now in "maintenance mode." We won't be able to prioritize this work.

As a reminder, per the [README.md](https://github.com/box/box-ios-sdk/blob/master/README.md):
> The Box iOS SDK in Objective-C (prior to v3.0.0) has been moved from the master branch to the [objective-c-maintenance branch](https://github.com/box/box-ios-sdk/tree/objective-c-maintenance). Going forward, the master branch will contain the iOS SDK in Swift, starting with v3.0.0.

Thanks, everyone!

@PJSimon
