### ISSUE TITLE
Framework not found BoxContentSDK

### ISSUE THREAD

**Issue by DeArchiTech** [box/box-ios-sdk#283]
Hello there, I am trying to link the Box SDK into a project that I am currently working on.
I followed your instruction and tried to add the SDK after I did 'Pod Install'
However, I am still getting a Framework not found issue, any idea of how to proceed forward?

I have tried to modify 'Framework search Paths' , adding the folder to 'Linked Frameworks and Libraries' and adjusting 'Copy Bundle Resources' but still no luck

![screen shot 2016-12-09 at 11 54 20 am](https://cloud.githubusercontent.com/assets/3968317/21062541/46802d3c-be06-11e6-9e35-934757830085.png)

Could you please provide a more detailed instruction of how to set up the SDK with an existing App? Thank you

**Comment by fagg** [comment]
I am seeing a similar issue.

![screen shot 2016-12-09 at 16 44 34](https://cloud.githubusercontent.com/assets/1742468/21065534/d3501466-be2e-11e6-8f43-7a4f869eb79b.png)

**Comment by crousselle** [comment]
Hello @noobiehacker @fagg , and thanks for using our SDK !
I was able to reproduce this. We will investigate and report to you guys as soon as we fix this. 
What version of CocoaPods are you using ? (you can find this by running `pod --version` in the terminal.
Thanks and have a great weekend !

**Comment by fagg** [comment]
@crousselle Thanks for your reply.

    [fagg@statler][~][0] -> pod --version
    1.0.0

I actually managed to get this working. I ended up recreating my XCode project and it's now working.

**Comment by crousselle** [comment]
@fagg @noobiehacker it looks like this is a project configuration issue. 
In both of your screenshots the "Pods" xcode project is not visible in your workspace, which is why the sdk is not found on compilation. 
In your `Podfile` file, make sure you have a line specifying the workspace that needs to be used for your Pods. (https://guides.cocoapods.org/using/using-cocoapods.html). 
`workspace 'MyWorkspace'`
After updating your pods again, if you open the workspace again, the Pods project should appear and compilation succeed.
Let me know if that helps, thanks !

**Comment by DeArchiTech** [comment]
@crousselle  Thank you, that resolves the issue :)
