### ISSUE TITLE
Does this library support Single Sign On across multiple apps using this library?

### ISSUE THREAD

**Issue by kunalbshah** [box/box-ios-sdk#284]
Hello there, we have a couple in-house iOS apps already using the Box SDK.  We’re trying to use it with a new in-house iOS app, and had a question. 
- Does the Box iOS SDK implement SSO feature? i.e. if two app on the same iOS device uses Box API authentication, then user logged into one app will not require logging into the second app. The second app will fetch the user logged in session/ information from the first app.

**Comment by boxtcarpel** [comment]
@kunalbshah Thank you for using the SDK and for reaching out!

We do have this feature, however only the Box App (https://itunes.apple.com/us/app/id290853822) can be an authentication "parent" app currently. So if the user is logged in to the Box app on their device, other apps that use the Box iOS SDK can do app-to-app authentication instead of making the user enter their credentials manually again.

If you are interested in this, we can help you get this configured, there is one change we have to make on our back end for your application to allow it to be a "child" app for this type of authentication.

**Comment by kunalbshah** [comment]
@boxtcarpel - Thanks for your quick response. Yes, we would be interested in exploring this App-to-App authentication. Can you please give us more detail about how to setup this up and share info with you? I have already created a test app on the box developer portal. 

I was trying to integrate this api by following the steps mentioned in the 'README' section. I followed the below steps and came across the SSO behavior.

1. I had two custom apps on my device with the box api integrated and shared keychain enabled. 
2. I launched the first app on my iOS device, logged in to box with my credentials and then launched the second app. 
3. When I tried to login in to box in the second app, it din't launched the box login page but the call back handler was able to fetch the user details of the first app.

Is this an intentional behavior of the api? Please let me know if you need more clarification.

**Comment by boxtcarpel** [comment]
Hi @kunalbshah the best way to proceed would be to open a developer support ticket (https://docs.box.com/page/support) and reference this ticket so we can help you directly.

At first glace, the steps you're description do not appear to the expected behavior to me, but we probably need more details to make sure we're fully understanding what you are describing here.
