### ISSUE TITLE
Persisting the login step for Box user

### ISSUE THREAD

**Issue by DeArchiTech** [box/box-ios-sdk#298]
Hello everyone, this is a general question not too sure if this is the right place to post it.

I was wondering is there a way to persist user credentials so users do not have to log in every-time the user wants to upload information to BOX?

Also does anyone know how long does the Authorization Token remains valid?  (How long does it take for it to be expired?)

Cheers, will be waiting for your response!~

**Comment by crousselle** [comment]
Hi @noobiehacker,

Thank you for using our SDK and reaching out. 

The SDK actually already takes care of all the credentials persistence logic, which means that you should not have to write any code to keep your users logged in onto Box, we've already taken care of that for you :)
If you are seeing issues around this feature while integrating our SDK into your app, please let us know !

We store all credentials required in order to maintain the user logged in in the device's keychain, including the access token and refresh token.
The access token is valid for about an hour, whereas the refresh token is valid for 60 days. 
Our SDK automatically handles any access token expiration and refreshing.
As long as the user is not inactive for more than 60 days, or gets logged out in some other way (by their admin, etc.) they should remain logged in.

Hope this helps, do not hesitate if you have any additional questions, otherwise, feel free to close this issue.

Thanks

Clement

**Comment by DeArchiTech** [comment]
Hey Clement

Thank you very much for the response, whats the difference between the access token and refresh token??  Does the User need to "re-login" if the access token gets expired ? (Lets say after one hr?)

Cheers, have a good one

David

**Comment by crousselle** [comment]
No problem ! 

The access token is used to authenticate API calls.
The refresh token is used to obtain a new access token after it expires. (That way the user does not get logged out every hour). 

Box uses standard OAuth2 authentication in our APIs (and SDKs), you can read more about it here https://docs.box.com/docs/oauth-20. 

As we mentioned before, this logic is abstracted by our SDK and you should not have to deal with those scenarios yourself.
Can you tell us more about what you're trying to do, or what the problem is that you're encountering ?  

Thanks,

Clément

**Comment by DeArchiTech** [comment]
Thanks Clement, really appreciate your help!~
