### ISSUE TITLE
Issue with using Box SDK on Cocoapods while Gogle Analytics is included in the same pod file

### ISSUE THREAD

**Issue by Roshanalexander** [box/box-ios-sdk#312]
Until few days ago, everything worked fine on my Xcode project where I had both 'box-ios-sdk' and 'Google/Analytics' on my pod file. But today after doing 'pod update', if 'box-ios-sdk' is on my pod file along with 'Google/Analytics', compiling the project would give me a link error. Taking out 'box-iso-sdk' would solve the issue. The error is:

duplicate symbol _GSDK_NSClassFromString in:
    /Users/roshanalexander/Desktop/Test App/Pods/FirebaseCore/Frameworks/FirebaseCore.framework/FirebaseCore(overload_ce3e584daf18c5845423080510ce7a37.o)
    /Users/roshanalexander/Desktop/Test App/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities(overload.o)
duplicate symbol _GSDK_objc_getClass in:
    /Users/roshanalexander/Desktop/Test App/Pods/FirebaseCore/Frameworks/FirebaseCore.framework/FirebaseCore(overload_ce3e584daf18c5845423080510ce7a37.o)
    /Users/roshanalexander/Desktop/Test App/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities(overload.o)
duplicate symbol _GSDK_objc_getProtocol in:
    /Users/roshanalexander/Desktop/Test App/Pods/FirebaseCore/Frameworks/FirebaseCore.framework/FirebaseCore(overload_ce3e584daf18c5845423080510ce7a37.o)
    /Users/roshanalexander/Desktop/Test App/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities(overload.o)
duplicate symbol _GSDK_objc_lookUpClass in:
    /Users/roshanalexander/Desktop/Test App/Pods/FirebaseCore/Frameworks/FirebaseCore.framework/FirebaseCore(overload_ce3e584daf18c5845423080510ce7a37.o)
    /Users/roshanalexander/Desktop/Test App/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities(overload.o)
**ld: 4 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**
![screen shot 2017-01-27 at 10 04 23 pm](https://cloud.githubusercontent.com/assets/6432696/22393848/eb3b25b8-e4dd-11e6-9230-0d06c7725582.png)

**Comment by boxtcarpel** [comment]
Hi @Roshanalexander, thank you for using our SDK and for reaching out. The errors you included seem to indicate you have a duplicate symbols issue between FirebaseCore.framework and GoogleSymbolUtilities.framework, you might need to check Google's documentation or reach out to their support to see how to resolve that.
I did looks this up quickly and found this stack overflow post on a similar issue that seems to indicate it might be a problem introduced in version 3.11.1 of the Firebase framework - http://stackoverflow.com/questions/41839737/ld-4-duplicate-symbols-for-architecture-armv7-firebase-google.

I'm not sure why the problem seems to go away for when when removing the Box SDK from your podfile, but from the errors the problem appears to be with Google's Firebase.

Please let us know if we can help further. Good luck!

**Comment by Roshanalexander** [comment]
Thanks for the reply. I managed to fix this issue by changing from pod 'Google/Analytics' to pod 'GoogleAnalytics' which is a different pod for Google Analytics.

**Comment by boxtcarpel** [comment]
Glad to hear it. Let us know if there are any other issues, and good luck!
