### ISSUE TITLE
Retrieve Access Token

### ISSUE THREAD

**Issue by sugampandey** [box/box-ios-sdk#366]
Using the SDK, is there a way to retrieve the access_token and refresh_token once user has been authenticated? 

We basically want to achieve the following:
1. Have user authenticate their Box account on the iPhone using the SDK 
2. Retrieve the access token from (1) and pass it to our server side so that the server side can directly scan some documents from the Box account.

**Comment by boxtcarpel** [comment]
Hi @sugampandey, thanks for reaching out and for using our SDKs and APIs.

Sorry for the delayed response.

Yes, the access token can be retrieved from the SDK, however I don't think the pattern you're highlighting here is a way we'd recommend using our platform.
If you're building an in-house app to use with your company's Box implementation, this should be fine as long as it fulfills your needs. For general purpose distribution (on the App Store, for example) this is not a good approach since users may not expect that by using your app they are enabling a remote server to fully access their Box account. Alternatively, you may want to evaluate interacting with Box in your app and passing the file itself to your server (giving the server component access to one specific file at a time with user confirmation instead of the user's whole account).

You probably figured out how to do this by now, but if you need further help please let us know and we'll get back to you right away.

Thanks and good luck!
