### ISSUE TITLE
Huge number of compiler warning

### ISSUE THREAD

**Issue by rajeevku02** [box/box-ios-sdk#484]
I am using this sdk using carthage in an objective-c project. I am getting huge instances of a single compiler warning.  For example:

BoxContentClient+Folder.h

    - (BOXFolderRequest *)folderInfoRequestWithID:(NSString *)folderID;
    Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

Xcode Version: 9.2 (9C40b)

**Comment by jlawton** [comment]
Thank you for the report. Nullability annotations are a known deficiency for this SDK, that we'd like to fix. Adding them will change compatibility with existing Swift code, so it's good to have a request to help us prioritize this.

**Comment by PJSimon** [comment]
Hi @rajeevku02 and @jlawton !  We're closing this Enhancement Issue on the [objective-c-maintenance branch](https://github.com/box/box-ios-sdk/tree/objective-c-maintenance) since the Objective-C iOS SDK is now in "maintenance mode."  We won't be able to prioritize this work.

As a reminder, per the [README.md](https://github.com/box/box-ios-sdk/blob/master/README.md):
> The Box iOS SDK in Objective-C (prior to v3.0.0) has been moved from the master branch to the [objective-c-maintenance branch](https://github.com/box/box-ios-sdk/tree/objective-c-maintenance). Going forward, the master branch will contain the iOS SDK in Swift, starting with v3.0.0.

Thanks, everyone!

@PJSimon
