### ISSUE TITLE
Disappearing users

### ISSUE THREAD

**Issue by bazik123** [box/box-ios-sdk#493]
in past few months many of my clients report launching my app after 1-2 days and finding being logged out. all my tests suggest that somehow BOXContentClient.defaultClient is not seeing the (stored?) user info that was there when app was last open.

Are there any cases where this would normally happen? 

Do I need to worry about syncing something before closing the app, do the credentials silently get deleted when refresh token expires (this is unlikely as this happens after 1-2 days of inactivity, not 60 days), could BOXContentClient be finding something unexpected in keychain and return nil user without logging anything? Could the user info get removed from keychain if I try to access BOXContentClient in a backgroundFetch?

**Comment by scottliubox** [comment]
Hi @bazik123 ,
Thanks for bringing this issue to our attention. This is a known issue that we've been tracking for a little while. Just want to clarify a few things:

By not seeing user info, you mean BOXContentClient.defaultClient's user property is nil? If so that's the correct behavior after a logout, even if the logout was triggered by mistake. 

No, there is nothing that needs to be synced in ContentSDK before closing the app, even if an accidental logout takes place.

The keychain theory is definitely something worth looking into, and we'll investigate according.

Thanks again!

**Comment by bazik123** [comment]
thanks for responding. to clarify, yes, when the app launches BOXContentClient.defaultClient.user is nil even though all my logout calls are logged and I am not seeing my code logging out in previous sessions.

**Comment by thuyBox** [comment]
We fixed an issue where we could trigger early logout at https://github.com/box/box-ios-sdk/pull/503. If you could try out and let us know whether this fixes your issue. Thanks!

**Comment by bazik123** [comment]
I am a little confused, have you dropped cocoapods support at some point?

**Comment by thuyBox** [comment]
yes, v1.0.15 was our last CocoaPods compatible release https://github.com/box/box-ios-sdk/releases/tag/v1.0.15. Carthage is required after that release.

**Comment by Prithvijutur** [comment]
@bazik123 did https://github.com/box/box-ios-sdk/pull/503 fix your issue?

**Comment by bazik123** [comment]
seems fixed by #503
