### ISSUE TITLE
BOXFileThumbnailRequest support for JPG format

### ISSUE THREAD

**Issue by technicallyerik** [box/box-ios-sdk#553]
BOXFileThumbnailRequest doesn't appear to have the option to set the "extension" parameter, and is defaulted to PNG.

I think this should be able to be changed, since different sizes are available for PNG vs JPG, and PNG returns square images, and JPG returns images proportional to the original.

**Comment by Prithvijutur** [comment]
@technicallyerik That sounds useful to have. You can override the class or make a pull request back to us with a new property that allows the request to use a different subresource. Otherwise, we will add this field in the next release.

Also to note - We are moving to use box representations API 
(BOXFileRepresentationDownloadRequest) on the master branch allows you to request thumbnails of different sizes which preserve the aspect ratio on larger sizes.

**Comment by Prithvijutur** [comment]
@technicallyerik The latest release uses the [representations API](https://developer.box.com/reference#representations) and the SDK now supports requesting subtypes/dimensions as a parameter here https://github.com/box/box-ios-sdk/blob/master/BoxContentSDK/BoxContentSDK/Requests/BOXFileRepresentationDownloadRequest.m#L32.

**Comment by PreciselyAlyss** [comment]
Please reopen if the latest version of the SDK hasn't resolved this :)
