### ISSUE TITLE
SHA_DIGEST_LENGTH Problem with iOS 12

### ISSUE THREAD

**Issue by ghost** [box/box-ios-sdk#564]
Hello,

I install the box-is-sdk over cocoapods. It works fine with iOS 11 and under iOS 12 I get this error message in BoxHashHelper.m:

/Users/RWarnecke/repos/XCode/ios/Sprit-Rechner-Plus/Pods/box-ios-sdk/BoxContentSDK/BoxContentSDK/External/HashHelper/BOXHashHelper.m:131:26: Use of undeclared identifier 'SHA_DIGEST_LENGTH'

I found the issue #536, but the merged pull request doesn't assign to the cocoapods installation. Please can you fix it.

**Comment by ajmeerkhan** [comment]
Hello Box Team,
         Found the same problem. Please fix this ASAP.

@RWarnecke thanks for the issue post.

**Comment by jlawton** [comment]
Thanks for pointing out the issue. I'll review master and see where we can cut a release. We don't maintain the CocoaPods spec, and our official support is for linking via Carthage or manually from releases. I suspect the spec will also need a change to work for you.

**Comment by ghost** [comment]
Thank you for your response. Why you don't support CocoaPods ? Other frameworks are supported both CocoaPods and Carthage. My mind is that CocoaPods are a easy and smooth way to use frameworks from GitHub.

I hope you find an easy way to fix the problem with the cocoapods

**Comment by ajmeerkhan** [comment]
Thank you for your response @jlawton , please support CocoaPods also, its easy to use and integrate.

**Comment by cloakapps** [comment]
I just have the same problem.  Please support CocoaPods too. Thanks.

**Comment by dabeku** [comment]
Having the same issue here. Please support CocoaPods.

Imho a grown up SDK like this one should support multiple packaging frameworks.

**Comment by utagap** [comment]
#include <CommonCrypto/CommonDigest.h>  
->  #include <CommonCrypto/commonDigest.h> in BOXHashHelper.m (XCode10)

Please change the first character of "CommonDigest.h" to lower case.  'C' -> 'c'   

It sounds like nonsense, but build is succeeded on my iMac.

**Comment by ashokds** [comment]
Some relevant details on https://github.com/box/box-ios-sdk/issues/570 (Closed it as duplicate).

Please support cocoapods.

**Comment by utagap** [comment]
XCode header file bug.

Only Apple XCode team can fix this bug.

There exists module.modulemap file in the same header-folder for XCode10.
For XCode9 or the previous version, the module.modulemap file does not exist in the same header-folder.

In the module.modulemap file, 'CommonCrypto.h' is defined, So, 'CommonCrypto.h' is pre-compiled.
Also, 'CommonDigest.h' is defined in 'CommonCrypto.h'. So, 'CommonDigest.h' is pre-compiled, too.

In 'CommonDigest.h', 'COMMON_DIGEST_FOR_OPENSSL' is used. If it is defined, 'SHA_DIGEST_LENGTH' is defined.
But, 'CommonDigest.h' is pre-compiled, so 'COMMON_DIGEST_FOR_OPENSSL' is not defined at first. As result, 'SHA_DIGEST_LENGTH' is not defined.
For the reason, 'SHA_DIGEST_LENGTH' can not be defined although 'COMMON_DIGEST_FOR_OPENSSL' is defined and 'CommonDigest.h' is included in 'BOXHashHelper.m'.

One of the solution is to change included file name in 'BOXHashHelper.m'. I changed it to 'commonDigest.h' (the first character is lower case), so the XCode compiler does not use pre-compiled header.

The easiest way to fix is to use no module.modulemap file. But we can not fix by the way because the folder is an XCode folder. Or the best way is that compiler analizes order of defined strings in detailed even if pre-compiled header is used.

We only have to wait until Apple XCode team fixes it.

**Comment by utagap** [comment]
(PS)
There are some ways to fix as follows:

(1) Changes '#include <CommonCrypto/CommonDigest.h>' to '#include <CommonCrypto/commonDigest.h>'.

(2) Adds the following code after '#include <CommonCrypto/CommonDigest.h>'

    #ifndef SHA_DIGEST_LENGTH
    #define SHA_DIGEST_LENGTH CC_SHA1_DIGEST_LENGTH
    #endif

But these ways are temporary ones. I desire BOX team contacts Apple XCode team to resolve the issue quickly.

* I am not a member of the BOX team. I am one of the persons having the issue.

**Comment by utagap** [comment]
I found the solution.

'COMMON_DIGEST_FOR_OPENSSL' is not defined in 'BOXHashHelper.m' as follows.

// #define COMMON_DIGEST_FOR_OPENSSL  
#include <CommonCrypto/CommonDigest.h> 

And, 'COMMON_DIGEST_FOR_OPENSSL' is defined as Preprocessor Macros in Build Settings instead.

I check. it is OK.

**Comment by Jeevanson** [comment]
I've the same problem. Please provide support for cocoapords too. Thanks

**Comment by ghost** [comment]
Is there a plan when we get the support for cocoapods ?

**Comment by Prithvijutur** [comment]
Unfortunately we have no plan to support cocoapods as of now

**Comment by ghost** [comment]
All other frameworks has the choice to select cocoa pods or carthage. This is not a good support. All my projects has frameworks with cocoa pods. Only for box I must build this framework with carthage. It is more work to service my apps.

Question:
If the source code here from GitHub the same as I install it over carthage ?

**Comment by mattwiller** [comment]
@RWarnecke Yes, you should be able to check out a release tag from this repo and build it yourself if you want to.

**Comment by josejhj2** [comment]
Does installing with Carthage solve the issue? Or is the only solution to modify the source file  BOXHashHelper.m ?

**Comment by dabeku** [comment]
@josejhj2 Yes, using Carthage resolves the issue but might introduce another packaging management system if you use pods as well for other libraries.
