### ISSUE TITLE
Bringing back CocoaPods support

### ISSUE THREAD

**Issue by bvirlet** [box/box-ios-sdk#606]
Hi Box Team,

You made the choice a couple years ago to switch to Carthage only. While I understand why you'd want to simplify this, this has multiple drawbacks.

For us is quite a bummer, we are integrating Box in our apps through an intermediate pod. 

Eg. our app(s) -> our private pod -> box-ios-sdk pod.

Unfortunately, we have no way for us to do:

our app(s) -> our private pod -> box-ios-sdk Carthage.

For now we are stuck on an old version of the Box SDK.

Supporting Cocoapods which is still a standard in the iOS community would be greatly appreciated.

Thanks!

**Comment by ghost** [comment]
Look at this [post](https://github.com/box/box-ios-sdk/issues/564#issuecomment-457012769) there is the answer about cocoa pods. I had changes at all my apps to Carthage for the iOS Box SDK.

**Comment by mattwiller** [comment]
@bvirlet @RWarnecke This is on our team's roadmap; we're planning to build out support for Cocoapods in the next major version of the SDK.  Since we're focusing our efforts on building out the new version, we're not currently planning to backport Cocoapods support to the current version.  We understand that this is a high-priority feature for many of our users, and we appreciate your patience as we work towards building a better SDK that we think will help support developers better!

**Comment by redbug26** [comment]
Yes. Please.
Cocoapods is still in 1.0.14... And doesn't have the UIWebView fix needed for ITMS-90809

**Comment by PJSimon** [comment]
Hi @bvirlet and @RWarnecke!  We're closing this Enhancement Issue on the [objective-c-maintenance branch](https://github.com/box/box-ios-sdk/tree/objective-c-maintenance) since CocoaPods is supported on the current version of the SDK (in Swift).

As a reminder, per the [README.md](https://github.com/box/box-ios-sdk/blob/master/README.md):
> The Box iOS SDK in Objective-C (prior to v3.0.0) has been moved from the master branch to the [objective-c-maintenance branch](https://github.com/box/box-ios-sdk/tree/objective-c-maintenance). Going forward, the master branch will contain the iOS SDK in Swift, starting with v3.0.0.

@redbug26, per your comment, the good news is that the change to from UIWebView to WKWebView was [recently committed](https://github.com/box/box-ios-sdk/pull/715) on the objective-c-maintenance branch!

Thanks, everyone!

@PJSimon
