### ISSUE TITLE
Apple Review

### ISSUE THREAD

**Issue by Xcdmau5** [box/box-ios-sdk#647]
After uploading the App to appstoreconnect,we receive this message:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

I checked, that box sdk (BOXAuthorizationViewController) is using UIWebView.
I think the Migrated from UIWebView to WKWebView is needed.

**Comment by PJSimon** [comment]
Hi @Xcdmau5,

Thanks for reporting this issue.  This appears to only be a warning that Apple will **eventually** stop accepting submissions of apps that reference UIWebView at some point in the future.  We are currently working on an all-new iOS SDK, written in Swift, which shouldn’t have this issue because it won’t use UIWebView.  

Now, since Apple only recently deprecated this class in iOS 12, and since it appears that UIWebView is in the iOS 13 Beta (version 2), then I would think that there shouldn’t be an issue in continuing to use it until the new Box iOS SDK is released later this year or very early next year.  Please let us know if you run into any issues in getting your application accepted by Apple, in the meantime.

I'm going to close this issue for now.

Thanks!

Patrick
