### ISSUE TITLE
Getting crash mostly after uploading more than 5 files

### ISSUE THREAD

**Issue by bawanevaibhavi** [box/box-ios-sdk#734]
application getting crash after uploading any type of file. We are using Objective-maintenance (https://github.com/box/box-ios-sdk/tree/objective-c-maintenance) branch for development. 

Error: Box API Operation Thread (18): EXC_BAD_ACCESS (code=1, address=0x10)

![crash](https://user-images.githubusercontent.com/30460869/87557607-bc6fd200-c6d5-11ea-99f1-281001e64f81.png)

**Comment by bawanevaibhavi** [comment]
![Screenshot 2020-07-16 at 4 15 17 PM](https://user-images.githubusercontent.com/30460869/87673894-dae7d300-c792-11ea-9e41-55ff951c67d1.png)

getting null data in variables

**Comment by PJSimon** [comment]
Hi @bawanevaibhavi ,

Unfortunately, since the Obj-C code base is in "maintenance mode" we are only providing critical security updates for it so we can focus our resources on the Swift code base.  I'm going to leave this question open in case some others in the community are able to help.  Sorry about that!  Thanks for understanding.

If you resolve this, please post it here to help others in the future!

**Comment by vikrambatra08** [comment]
Hi @PJSimon , 

I am also facing the same issue in my app after switching it to "Objective c maintenance branch". My app is developed using Objective C language. It would be really appreciated if you could fix this. Or please suggest any alternatives to handle this if you have any.

Thanks!
