### ISSUE TITLE
Redirect information on the grant access screen

### ISSUE THREAD

**Issue by dibelogrivaya** [box/box-ios-sdk#874]
Hello!

I can't understand, why I see this information in the red box (granting access will redirect ...) and what should I do to hide it. 
I use **BoxSDK (5.2.1)**.

![Simulator Screen Shot - iPhone 14 Pro - 2022-10-06 at 19 42 19](https://user-images.githubusercontent.com/1580342/194385850-fc80792e-f719-417c-8702-dbf8a7fc87d7.png)

Thanks!

**Comment by arjankowski** [comment]
Hi @dibelogrivaya,

During the OAuth flow user is redirected to log in page, and then to the page with requested scopes and option to approve, where you can see this message `Granting access will redirect to <YOUR_REDIRECT_URL>`.  This is what it looks like in the box regardless of the system/sdk/web browser.  Because of that you don't have any option in SDK itself to hide this redirect_url. 

If you want to ask if there are places other than SDK to hide this message, e.g. admin panel, you can ask about it here [here](https://support.box.com/hc/en-us/community/topics/360001932973-Platform-and-Developer-Forum).

From the other hand, you can also use different authentication method that we also support in our SDKs -> CCG. It's much easier to use than OAuth and you can read about it and how to use it on iOS [here](https://github.com/box/box-ios-sdk/blob/main/docs/usage/authentication.md#client-credentials-grant). in CCG authentication takes place without integration with a web browser, so no data will be displayed.

I hope this helps you.
Artur
