### ISSUE TITLE
`getOAuth2Client` completion closure not called during SSO sign-in with Microsoft Intune and Edge

### ISSUE THREAD

**Issue by yamamichi-datt** [box/box-ios-sdk#922]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

When I use `BoxSDK.getOAuth2Client(tokenInfo:tokenStore:context:completion:)` to sign in via Single Sign on (SSO), the `completion` closure is not called.

I have customers with devices managed by Microsoft Intune and Box accounts with SSO login.  
Also, my customers have conditional access to my app with Microsoft Intune and must authenticate using Microsoft Edge for SSO sign-in.

It works fine for personal accounts and SSO logins that do not require Edge.

Does the authentication process (ASWebAuthenticationSession) for box-ios-sdk work when the app is in the background?

### Steps to Reproduce

I created a sample app with minimal implementation.  
The app has only a "Login" button, and tapping this button will try to log in to Box using `BoxSDK.getOAuth2Client(tokenInfo:tokenStore:context:completion:)`.

1. Launch the app.
1. Tap the "Login" button.
1. The in-app browser opens and the login form appears.
1. Switch to SSO login from "Use Single Sign On (SSO)" link.
1. Enter an organization's email address (if necessary, password too).
1. "You can't get there from here" and the "Launch in Edge" button appears.
1. Tap the "Launch in Edge" button.
1. Edge is automatically launched.
1. Sign in to the organization's account, if necessary, and tap the "Allow access to box" button.
1. The process is automatically returned to the app.
1. The issue occurs at this time. The in-app browser is not closed and the `completion` closure to receive the result is never called.

### Expected Behavior

I expect the in-app browser for authentication to be closed and the `completion` closure to be called, regardless of the success or failure of the login.

### Error Message, Including Stack Trace

I cannot see any errors about box-ios-sdk and in-app browser is stuck on screen to redirect to Edge.

### Screenshots

Please see the following screen recording.

![312385743-d57acdab-7fef-4392-a8d6-0e7b7b99f103](https://github.com/box/box-ios-sdk/assets/163077017/2c928f5f-e28c-4b3d-8e98-2731f281275b)

### Versions Used

iOS SDK: 5.5.0
iOS Preview SDK: I did not check.
iOS: 17.2
Xcode: 15.3 (15E204a)

[sdk-docs]: https://github.com/box/box-ios-sdk/tree/v5.5.0/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-ios-sdk/search?type=Issues

**Comment by arjankowski** [comment]
Hi @yamamichi-datt,

OAuth authentication has been implemented as you indicated using `ASWebAuthenticationSession`, which relies on the built-in browser in iOS (Safari). For the authentication to proceed successfully, the entire process must take place within the opened browser because after user authentication, the authentication provider redirects the browser to a URL that uses the callback scheme. The browser detects the redirect, dismisses itself, and passes the complete URL to your app by calling the closure you specified during initialization.

When we launch a different browser, such as Edge in your case, Safari is unable to detect the redirection, which is what we see in your recording.

As a workaround, you can ask your customer's admin to turn off the exclusion of Safari on the devices in Microsoft Intune . This will allow the users to sign in using the System Browser.

Additionally, if that is not possible, you can use CCG authentication in your application, about which you can learn more [here](https://github.com/box/box-ios-sdk/blob/main/docs/usage/authentication.md#client-credentials-grant).

I hope this helps,
Artur

**Comment by yamamichi-datt** [comment]
Hello, @arjankowski.

Thank you for your help.

> Additionally, if that is not possible, you can use CCG authentication in your application, about which you can learn more here.

Okay, I will try CCG authentication.

As my question has now been resolved, may I close this issue?

Best Regards,

Yamamichi
